import { GymPreview } from "../types";

export const gyms: GymPreview[] = [
  {
    id: 1,
    name: "더클라임 강남",
    location: "서울 강남구 테헤란로",
    gradeColors: [
      "#ffffff",
      "#f4d35e",
      "#90be6d",
      "#43aa8b",
      "#277da1",
      "#ee964b",
      "#d1495b",
      "#7b2cbf",
      "#252422",
    ],
    easyPercentage: 65,
    hardPercentage: 35,
    staticPercentage: 70,
    dynamicPercentage: 30,
  },
  {
    id: 2,
    name: "피커스 종로",
    location: "서울 종로구 돈화문로",
    gradeColors: [
      "#ffffff",
      "#f4d35e",
      "#90be6d",
      "#43aa8b",
      "#277da1",
      "#ee964b",
      "#d1495b",
      "#7b2cbf",
      "#252422",
    ],
    easyPercentage: 20,
    hardPercentage: 80,
    staticPercentage: 35,
    dynamicPercentage: 65,
  },
  {
    id: 3,
    name: "서울숲 클라이밍",
    location: "서울 성동구 성수이로",
    gradeColors: [
      "#ffffff",
      "#f4d35e",
      "#90be6d",
      "#43aa8b",
      "#277da1",
      "#ee964b",
      "#d1495b",
      "#7b2cbf",
    ],
    easyPercentage: 50,
    hardPercentage: 50,
    staticPercentage: 60,
    dynamicPercentage: 40,
  },
  {
    id: 4,
    name: "볼더프렌즈 홍대",
    location: "서울 마포구 양화로",
    gradeColors: [
      "#ffffff",
      "#f4d35e",
      "#90be6d",
      "#43aa8b",
      "#277da1",
      "#ee964b",
      "#d1495b",
      "#7b2cbf",
    ],
    easyPercentage: 70,
    hardPercentage: 30,
    staticPercentage: 45,
    dynamicPercentage: 55,
  },
  {
    id: 5,
    name: "클라이밍파크 한강",
    location: "서울 영등포구 여의대로",
    gradeColors: [
      "#ffffff",
      "#f4d35e",
      "#90be6d",
      "#43aa8b",
      "#277da1",
      "#ee964b",
      "#d1495b",
      "#7b2cbf",
      "#252422",
    ],
    easyPercentage: 60,
    hardPercentage: 40,
    staticPercentage: 75,
    dynamicPercentage: 25,
  },
  {
    id: 6,
    name: "알레 클라이밍 잠실",
    location: "서울 송파구 올림픽로",
    gradeColors: [
      "#ffffff",
      "#f4d35e",
      "#90be6d",
      "#43aa8b",
      "#277da1",
      "#ee964b",
      "#d1495b",
      "#7b2cbf",
      "#252422",
    ],
    easyPercentage: 55,
    hardPercentage: 45,
    staticPercentage: 50,
    dynamicPercentage: 50,
  },
];
